apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vote
  name: vote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
      labels:
        app: vote
    spec:
      containers:
      - image: mdbott/examplevotingapp_vote:1.0.1
        name: vote
        ports:
        - containerPort: 80
          name: vote
        securityContext:
          allowPrivilegeEscalation: false
